export const SUPABASE_URL = 'https://buldxeuoqywlgzcutzch.supabase.co'
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1bGR4ZXVvcXl3bGd6Y3V0emNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMzQwMDEsImV4cCI6MjA1MTgxMDAwMX0.WXXhRC0gSDAqM41kFuyHwmfAdhDOFGhRQnG1iy-DTl8'
